// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZpHmwmXp7uiuHHntXBTcuMkkrnGsXhFY',
    appId: '1:485534946769:web:d6871b833b86584f74bcf0',
    messagingSenderId: '485534946769',
    projectId: 'my-food-cc762',
    authDomain: 'my-food-cc762.firebaseapp.com',
    storageBucket: 'my-food-cc762.firebasestorage.app',
    measurementId: 'G-7L27R3HYPC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqyH4jU5dr_XAOMvdokMWwPNWDX8hBpHM',
    appId: '1:485534946769:android:b3fb2aa0ca0f658474bcf0',
    messagingSenderId: '485534946769',
    projectId: 'my-food-cc762',
    storageBucket: 'my-food-cc762.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc4qaWriPi70eS8DkhE1ayG2I3Stk7D-g',
    appId: '1:485534946769:ios:cec0a11081ba7aff74bcf0',
    messagingSenderId: '485534946769',
    projectId: 'my-food-cc762',
    storageBucket: 'my-food-cc762.firebasestorage.app',
    iosBundleId: 'com.example.myfood',
  );
}
